name: Frontend CI

on:
  pull_request:
    branches:
      - develop
      
jobs:
  tmp:
    name: "tmp"
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout for GitHub Actions
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: List PR commits
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh pr view ${{ github.event.pull_request.number }} --json commits
